# More handy prefix
unbind-key C-b
set-option -g prefix C-a

# Clear
bind -n C-k clear-history

# Activity monitoring
set-window-option -g monitor-activity on

set-option -g default-terminal "xterm"
set-window-option -g xterm-keys on
# mouse selections
set-option -g mouse on

set -g history-limit 10000

# Vi copypaste mode
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection
